manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: diogodoreto
      url-base: https://github.com/DiogoDoreto
  projects:
    - name: zmk
      remote: diogodoreto
      revision: waterfowl-encoders
      import: app/west.yml
   #- name: zmk
   #  remote: infused-kim
   #  revision: sofle
   #  import: app/west.yml
   #- name: zmk
   #  remote: zmkfirmware
   #  revision: main
   #  import: app/west.yml
  self:
    path: config
