manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: dnlbauer
      url-base: https://github.com/dnlbauer
  projects:
      #    - name: zmk
      #remote: dnlbauer
      #revision: waterfowl-encoders
      #import: app/west.yml
   #- name: zmk
   #  remote: infused-kim
   #  revision: sofle
   #  import: app/west.yml
   - name: zmk
     remote: zmkfirmware
     revision: main
     import: app/west.yml
  self:
    path: config
